#!/usr/bin/env bash

# Check if correct number of parameters are provided
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables
FILE_PATH=$1
SERVER_IP=$2
USERNAME=$3
SSH_KEY_PATH=$4

# Construct the SCP command
SCP_COMMAND="scp -o StrictHostKeyChecking=no -i $SSH_KEY_PATH $FILE_PATH $USERNAME@$SERVER_IP:~/"

# Execute the SCP command
$SCP_COMMAND

# Check if the SCP command was successful
if $SCP_COMMAND; then
    echo "File transferred successfully."
else
    echo "Error transferring file."
fi
