#!/usr/bin/env bash
#Installs HAProxy with the following configurations:
#management is enabled via the init script
#the requests are distributed using a round-robin algorithm.

sudo apt-get update
sudo apt-get install -y haproxy

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

cat <<EOT | sudo tee -a /etc/haproxy/haproxy.cfg
frontend www.afriyie.tech
    timeout client  30000
    bind 0:80
    default_backend www.afriyie.tech_backend

backend www.afriyie.tech_backend

    timeout connect  3000
    timeout server  30000
    balance roundrobin
    server 228560-web-01 52.91.157.33 check
    server 228560-web-02 3.85.148.37check

EOT

sudo service haproxy restart
