#!/usr/bin/env bash
#a bash script that stops 4-to_infinity_and_beyond
#without the use of kill or killall

terminate()
{
        echo "T am invincible!!!"
        pkill -f "7-highlander"
        exit 0
}

trap terminate SIGTERM
while true;
do
        sleep 1
done
