#!/usr/bin/env bash
#a Bash script that configures an Ubuntu server with the below requirements
#localhost resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8

localhost_mapping="127.0.0.2 localhost"
facebook_mapping="8.8.8.8 facebook.com"
cp /etc/hosts ~/hosts.new
echo "localhost_mapping" > ~/hosts.new
echo "facebook_mapping" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
