#!/usr/bin/env bash
# a Bash script that creates an RSA key pair
key_file="school"

# Generate RSA key pair with 4096 bits and passphrase
ssh-keygen -t rsa -b 4096 -f "$key_file" -N "betty"

echo "RSA key pair created successfully."
echo "Private key: $key_file"
